frame_id: "world"
embed_trajectory_delta_t: 1.0 # seconds (prints warning if delta exceeds, not strictly enforced. ) 
rpgo:
  odom_trans_threshold: 0.001
  odom_rot_threshold: 0.001
  pcm_trans_threshold: 0.001
  pcm_rot_threshold: 0.001
  gnc_alpha: 0
