frame_id: "world"
embed_trajectory_delta_t: 0.1 # seconds (prints warning if delta exceeds, not strictly enforced. )
num_interp_pts: 4 # use n controls points when interpolating for full deformed mesh
interp_horizon: 10.0 # only consider control points last observed within t seconds
rpgo:
  odom_trans_threshold: 0.001
  odom_rot_threshold: 0.005
  pcm_trans_threshold: 0.001
  pcm_rot_threshold: 0.005
  gnc_alpha: 0
add_initial_prior: true
covariance:
  odom: 1.0e-06
  loop_close: 1.0e-04
  prior: 1.0e-08
  mesh_mesh: 1.0e-02
  pose_mesh: 1.0e-04