frame_id: "world"
embed_trajectory_delta_t: 5.0 # seconds (prints warning if delta exceeds, not strictly enforced. )
num_interp_pts: 4 # use n controls points when interpolating for full deformed mesh
interp_horizon: 20.0 # only consider control points last observed within t seconds
trans_node_dist: 0.5
rot_node_dist: 1.0
rpgo:
  odom_trans_threshold: 0.05
  odom_rot_threshold: 0.01
  pcm_trans_threshold: -1
  pcm_rot_threshold: -1
  lm_diagonal_damping: true
  gnc_alpha: 0.99
  gnc_max_iterations: 100
  gnc_mu_step: 1.6
  gnc_cost_tolerance: 1.0e-05
  gnc_weight_tolerance: 1.0e-04
  gnc_fix_prev_inliers: true
add_initial_prior: false
covariance:
  odom: 1.0e-02
  loop_close: 5.0e-02
  prior: 1.0e-02
  mesh_mesh: 1.0e-02
  pose_mesh: 1.0e-02